services: 
  devop_app:
    image:  fariddoker/hello_docker

    ports: 
     - "9000:80"

  jenkins:
    build: /jenkins/.
    container_name: jenkin
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # si tu veux que Jenkins lance des conteneurs Docker
    restart: always

volumes:
  jenkins_home: