apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: devops
  rules:
  - http:
      paths:
      - path: /devops
        pathType: Prefix
        backend:
          service:
            name: devops
            port:
              number: 80